/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package LoginSyste;

import Enterprise.EnterpriseSurface;
import User.UserSurface;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author 17433
 */
public class Customer_Login_Interface extends javax.swing.JFrame {

    /**
     * Creates new form CUSTOMER
     */
    public Customer_Login_Interface() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jPasswordField3 = new javax.swing.JPasswordField();
        jLabel14 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        customer_registration = new javax.swing.JButton();
        Customer_login = new javax.swing.JButton();
        return_cli_mi = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LoginSyste/pioneer.png"))); // NOI18N
        jLabel1.setToolTipText("");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, -1));

        jLabel13.setFont(new java.awt.Font("幼圆", 1, 30)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Username");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 570, 150, 40));

        jTextField1.setFont(new java.awt.Font("幼圆", 1, 30)); // NOI18N
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 564, 250, -1));

        jLabel6.setFont(new java.awt.Font("方正粗黑宋简体", 1, 36)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Login");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 680, 190, 70));

        jPasswordField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField3ActionPerformed(evt);
            }
        });
        getContentPane().add(jPasswordField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 620, 255, 40));

        jLabel14.setFont(new java.awt.Font("幼圆", 1, 30)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Password");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 620, 150, 40));

        jLabel4.setFont(new java.awt.Font("方正粗黑宋简体", 1, 36)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Register");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 680, 190, 70));

        customer_registration.setFont(new java.awt.Font("方正舒体", 3, 50)); // NOI18N
        customer_registration.setForeground(new java.awt.Color(255, 255, 255));
        customer_registration.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LoginSyste/main interface button.png"))); // NOI18N
        customer_registration.setAutoscrolls(true);
        customer_registration.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        customer_registration.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                customer_registrationMouseClicked(evt);
            }
        });
        customer_registration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customer_registrationActionPerformed(evt);
            }
        });
        getContentPane().add(customer_registration, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 680, 190, 70));

        Customer_login.setFont(new java.awt.Font("方正舒体", 3, 50)); // NOI18N
        Customer_login.setForeground(new java.awt.Color(255, 255, 255));
        Customer_login.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LoginSyste/main interface button2.png"))); // NOI18N
        Customer_login.setAutoscrolls(true);
        Customer_login.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Customer_login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Customer_loginMouseClicked(evt);
            }
        });
        Customer_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Customer_loginActionPerformed(evt);
            }
        });
        getContentPane().add(Customer_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 680, 190, 70));

        return_cli_mi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LoginSyste/back.png"))); // NOI18N
        return_cli_mi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                return_cli_miMouseClicked(evt);
            }
        });
        getContentPane().add(return_cli_mi, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 707, 50, 50));

        jPanel1.setBackground(new java.awt.Color(251, 250, 248));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 760, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jPasswordField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField3ActionPerformed

    private void Customer_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Customer_loginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Customer_loginActionPerformed

    private void customer_registrationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customer_registrationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_customer_registrationActionPerformed

    private void return_cli_miMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_return_cli_miMouseClicked
        // TODO add your handling code here:
        Main_Interface MI = new Main_Interface();
        MI.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_return_cli_miMouseClicked

    private void customer_registrationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_customer_registrationMouseClicked
        // TODO add your handling code here:
        Customer_registration_interface cri=new Customer_registration_interface();
        cri.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_customer_registrationMouseClicked

    private void Customer_loginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Customer_loginMouseClicked
        // TODO add your handling code here:
        boolean IsRight = false;
        Connection con;
        String driver = "com.mysql.jdbc.Driver";
        String url = "jdbc:mysql://localhost:3306/db_Pioneer";
        String user = "root";
        String password = "123456";
        try
        {
            
             Class.forName(driver);
             con = DriverManager.getConnection(url,user,password);
             if(!con.isClosed())
                 System.out.println("Succeeded connecting to the Database!");
             Statement statement = con.createStatement();
             String sql = "select * from user_info";
             ResultSet rs = statement.executeQuery(sql);

             String UserName = null;
             String id = null;
             String Password = null;
             while(rs.next())
             {
                 id = rs.getString("ID");
                 UserName = rs.getString("UserName");
                 Password = rs.getString("Password");
                 if(UserName.equals(jTextField1.getText()))
                 {
                     if(Password.equals(jPasswordField3.getText()))
                     {
                         IsRight = true;
                     }
                 }
             }
             rs.close();
             con.close();
         }
         catch(ClassNotFoundException e)
         {   
             e.printStackTrace();   
         }
         catch(SQLException e)
         {
             e.printStackTrace();  
         }
         catch (Exception e)
         {
             e.printStackTrace();
         }
         finally{ }
        if(IsRight)
        {
            UserSurface main = new UserSurface(jTextField1.getText());
            this.dispose();
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Wrong Username or Password!",
                "Failed", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_Customer_loginMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Customer_Login_Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Customer_Login_Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Customer_Login_Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Customer_Login_Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Customer_Login_Interface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Customer_login;
    private javax.swing.JButton customer_registration;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton return_cli_mi;
    // End of variables declaration//GEN-END:variables
}
