/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package LoginSyste;

/**
 *
 * @author 17433
 */
public class Main_Interface extends javax.swing.JFrame {

    /**
     * Creates new form MerchantLoginInterface
     */
    public Main_Interface() {
        initComponents();
        //Main_Interface mi = new Main_Interface();
        // mi.setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollBar1 = new javax.swing.JScrollBar();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        customerlogin = new javax.swing.JButton();
        operatorlogin = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LoginSyste/pioneer.png"))); // NOI18N
        jLabel1.setToolTipText("");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 550));

        jLabel2.setFont(new java.awt.Font("方正舒体", 3, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Customer");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 590, 230, 70));

        jLabel4.setFont(new java.awt.Font("方正舒体", 3, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Merchant");
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 590, 230, 70));

        customerlogin.setFont(new java.awt.Font("方正舒体", 3, 50)); // NOI18N
        customerlogin.setForeground(new java.awt.Color(255, 255, 255));
        customerlogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LoginSyste/main interface button2.png"))); // NOI18N
        customerlogin.setAutoscrolls(true);
        customerlogin.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        customerlogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                customerloginMouseClicked(evt);
            }
        });
        customerlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerloginActionPerformed(evt);
            }
        });
        getContentPane().add(customerlogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 590, 230, 70));

        operatorlogin.setFont(new java.awt.Font("方正舒体", 3, 50)); // NOI18N
        operatorlogin.setForeground(new java.awt.Color(255, 255, 255));
        operatorlogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LoginSyste/main interface button2.png"))); // NOI18N
        operatorlogin.setAutoscrolls(true);
        operatorlogin.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        operatorlogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                operatorloginMouseClicked(evt);
            }
        });
        operatorlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                operatorloginActionPerformed(evt);
            }
        });
        getContentPane().add(operatorlogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 590, 230, 70));

        jTextArea1.setBackground(new java.awt.Color(251, 250, 248));
        jTextArea1.setColumns(20);
        jTextArea1.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea1.setRows(5);
        jTextArea1.setBorder(null);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 600, 760));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void customerloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerloginActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_customerloginActionPerformed

    private void operatorloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_operatorloginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_operatorloginActionPerformed

    private void customerloginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_customerloginMouseClicked
        // TODO add your handling code here:
        Customer_Login_Interface cli = new Customer_Login_Interface();
        cli.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_customerloginMouseClicked

    private void operatorloginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_operatorloginMouseClicked
        // TODO add your handling code here:
        Merchant_Login_Interface mli = new Merchant_Login_Interface();
        mli.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_operatorloginMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main_Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main_Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main_Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main_Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main_Interface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton customerlogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton operatorlogin;
    // End of variables declaration//GEN-END:variables
}
